### ISSUE TITLE
Improve output

### ISSUE THREAD

**Issue by pocke** [pocke/gry#7]
```yaml
Style/Foo:
  EnforcedStyle: bar # 2 warnings
  SupportedStyle:
    - baz # 10 warnings
    - poyo # 100 warnings
```
